lannguage: python
python:
  - "2.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install -qq python-pip tcpdump unzip libpcap-dev
  - sudo pip install -r requirements.txt
script:
  - py.test
